# Generated by Django 5.0.6 on 2024-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
